// Archivo de layout principal de la app.
// Define la estructura base y el layout global de la aplicación.

import type { Metadata } from "next";
import  BackgroundFX from "@/components/BackgroundFX";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Nevora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Nerova</title>
        <link rel="icon" href="/images/logo.png" />
      </head>
      <body className="relative min-h-screen bg-[#0A0D1C] overflow-x-hidden text-white">
        <BackgroundFX />
        <Header />
        <main className="relative z-10">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
